# -*- coding: utf-8 -*-
"""saketto / クラフトサケ醸造所マスター (25蔵)

すべて 2026-05-30 時点で公式サイト・公式ECで一次ソース確認済み。
出典は ナレッジ/醸造所検証データ_20260530.md を参照。
"""

BREWERIES = [
    # ── 協会加盟9社 ──
    {
        "slug": "ine-to-agave",
        "name": "稲とアガベ醸造所",
        "name_kana": "イネトアガベ",
        "prefecture": "秋田県",
        "city": "男鹿市船川港船川新浜町",
        "region": "東北",
        "founded": "2021",
        "official_url": "https://inetoagave.com/",
        "philosophy": "男鹿の風土を醸す。米と米麹をフルーツやハーブと一緒に発酵させた新ジャンルのクラフトサケ。全量無肥料無農薬の自然栽培米、精米歩合90%統一。",
        "features": "アガベシロップを副原料に使う代表格。クラフトサケジャンル創設者格。",
        "association": True,
    },
    {
        "slug": "haccoba",
        "name": "haccoba",
        "name_kana": "ハッコウバ",
        "prefecture": "福島県",
        "city": "南相馬市小高区",
        "region": "東北",
        "founded": "2021",
        "official_url": "https://haccoba.com/",
        "philosophy": "かつての民俗的なドブロクづくりを現代的に表現し、クラフトビールの自由なカルチャーで日本酒を再編集。",
        "features": "クラフトサケジャンルの先駆者。「花酛」復刻＋ホップ・ハーブ・ベルギービール製法・バーボンバレル熟成も実験。",
        "association": True,
    },
    {
        "slug": "lagoon",
        "name": "LAGOON BREWERY",
        "name_kana": "ラグーンブリュワリー",
        "prefecture": "新潟県",
        "city": "新潟市北区前新田乙",
        "region": "中部",
        "founded": "2021",
        "official_url": "https://www.lagoon-brewery.com/home",
        "philosophy": "「感激できる、多様なおいしさ」をモットーに、極小規模と持続可能性にこだわった醸造。福島潟のほとりで地域素材を活用。",
        "features": "ブランド名は「翔空（しょうくう）」。果実・ホップ・トマト＋バジルまで副原料の幅が極めて広い。",
        "association": True,
    },
    {
        "slug": "librom",
        "name": "LIBROM",
        "name_kana": "リブロム",
        "prefecture": "福岡県",
        "city": "福岡市中央区高砂",
        "region": "九州",
        "founded": "2020",
        "official_url": "https://librom.jp/",
        "philosophy": "「自由な醸造スタイルで酒造りにロマンを。」社名はLIBERTA（自由）+ROMANZO（ロマン）の造語。米を主原料に果物・ハーブ・野菜・スパイスを副原料に。",
        "features": "九州・福岡県産の果物・ハーブ・野菜・スパイスを副原料に。バー併設の醸造所。",
        "association": True,
    },
    {
        "slug": "konohanano",
        "name": "木花之醸造所",
        "name_kana": "コノハナノジョウゾウショ",
        "prefecture": "東京都",
        "city": "台東区駒形",
        "region": "関東",
        "founded": "2020",
        "official_url": "https://konohanano-brewery.com/",
        "philosophy": "浅草の代表的観光地で国内外に誇れる名物の酒造りを。若い蔵人が活躍できる「新しい修行の場」として独立を支援。",
        "features": "浅草・駒形のどぶろく醸造所。ALL (W)RIGHT sake placeを併設しバーで提供。若手醸造家の修行拠点的役割。",
        "association": True,
    },
    {
        "slug": "happy-taro",
        "name": "ハッピー太郎醸造所",
        "name_kana": "ハッピータロウジョウゾウショ",
        "prefecture": "滋賀県",
        "city": "長浜市元浜町",
        "region": "関西",
        "founded": "2017",
        "official_url": "https://happytaro.jp/",
        "philosophy": "「醗酵でつなぐ、しあわせ」。糀屋ならではの完熟糀を使い、顔の見える生産者の原材料と伊吹山伏流水で醸す。",
        "features": "糀屋（発酵食品店）×どぶろくのハイブリッド。「something happy」シリーズで茶葉・八朔・黒文字など多彩な副原料を展開。",
        "association": True,
    },
    {
        "slug": "heiroku",
        "name": "平六醸造",
        "name_kana": "ヘイロクジョウゾウ",
        "prefecture": "岩手県",
        "city": "紫波郡紫波町日詰",
        "region": "東北",
        "founded": "2023",
        "official_url": "https://www.hiraroku.com/",
        "philosophy": "「百年の眠りから目覚めた酵母で醸す新時代の醸造酒」。日本酒の伝統を尊重しながら、発芽玄米・フルーツ果汁を活用。",
        "features": "古民家（平井邸）を改装した醸造所。発芽玄米ベースのRe:viveと、フルーツ果汁を重ねるlayerの2シリーズ展開。",
        "association": True,
    },
    {
        "slug": "pukupuku",
        "name": "ぷくぷく醸造",
        "name_kana": "プクプクジョウゾウ",
        "prefecture": "福島県",
        "city": "南相馬市小高区仲町",
        "region": "東北",
        "founded": "2022",
        "official_url": "https://note.com/pukupukubrewing/",
        "philosophy": "自然発酵（全量酵母無添加）とビール技法を掛け合わせ、「異文化との境界線を溶かした日本酒」を目指す。",
        "features": "全量酵母無添加×ビール技法のハイブリッド。元haccoba醸造責任者の立川氏が独立。木桶仕込みの全麹酒も展開。",
        "association": True,
    },
    {
        "slug": "adachi-noujo",
        "name": "足立農醸",
        "name_kana": "アダチノウジョウ",
        "prefecture": "大阪府",
        "city": "高槻市牧田町（富田団地内）",
        "region": "関西",
        "founded": "2024",
        "official_url": "https://adachi-noujo.com/",
        "philosophy": "「世界が驚く、唯一の日本酒を造りたい」。日本初の団地酒蔵。高槻産米と大阪農産物を発酵段階で添加。",
        "features": "日本初の「団地酒蔵」。最小規模の酒蔵でカフェ＆バー併設。クラフトサケ＋発酵ノンアル飲料の二軸展開。",
        "association": True,
    },
    # ── 協会非加盟15社 ──
    {
        "slug": "nondo",
        "name": "nondo（non°）",
        "name_kana": "ノンド",
        "prefecture": "岩手県",
        "city": "遠野市",
        "region": "東北",
        "founded": "2022",
        "official_url": "https://nondo-tono.life/",
        "philosophy": "遠野の風土と自然栽培「遠野1号」米から、無添加の米飲料・どぶろく・甘酒・米酢を醸す。",
        "features": "自然栽培「遠野1号」米。四代目佐々木要太郎が長年取り組む遠野のクラフトサケ。",
        "association": False,
    },
    {
        "slug": "fermenteria",
        "name": "Fermenteria",
        "name_kana": "ファーメンテリア",
        "prefecture": "宮城県",
        "city": "仙台市青葉区中央（仙台駅構内）",
        "region": "東北",
        "founded": "2024",
        "official_url": "https://fermenteria.co/",
        "philosophy": "駅ナカ約3.4坪のマイクロ醸造所から、米と麹でつくる生クラフトサケを発信。",
        "features": "「その他の醸造酒製造免許」取得（2024年7月）。果実等副原料も小ロット製造可能。運営は勝花藏株式会社。",
        "association": False,
    },
    {
        "slug": "yamane",
        "name": "やまね酒造",
        "name_kana": "ヤマネシュゾウ",
        "prefecture": "埼玉県",
        "city": "飯能市",
        "region": "関東",
        "founded": "2019",
        "official_url": "https://yamaneshuzo.jp/",
        "philosophy": "西川材の杉木桶で、埼玉県産米と地元素材を醸す。",
        "features": "副原料に飯能産の茶葉・蜂蜜・発芽玄米など、地元素材を活用。クラフトサケ醸造は2022年から本格化。",
        "association": False,
    },
    {
        "slug": "heiwa-kabutocho",
        "name": "平和どぶろく兜町醸造所",
        "name_kana": "ヘイワドブロクカブトチョウジョウゾウジョ",
        "prefecture": "東京都",
        "city": "中央区日本橋兜町",
        "region": "関東",
        "founded": "2022",
        "official_url": "https://www.heiwashuzou.co.jp/heiwa-doburoku-kabutocho",
        "philosophy": "和歌山「紀土」蔵元の平和酒造が、東京・兜町で都市型どぶろく醸造所を展開。",
        "features": "小豆・黒豆・ホップなど多彩な副原料と、日替わりの『本日のどぶろく』。和歌山「紀土」の平和酒造による都市型どぶろく醸造所。",
        "association": False,
    },
    {
        "slug": "heiwa-namba",
        "name": "平和どぶろく難波醸造所",
        "name_kana": "ヘイワドブロクナンバジョウゾウジョ",
        "prefecture": "大阪府",
        "city": "大阪市中央区難波（大阪タカシマヤB1）",
        "region": "関西",
        "founded": "2025",
        "official_url": "https://www.heiwashuzou.co.jp/",
        "philosophy": "平和酒造のどぶろくブルワリーパブ第2号店。自社栽培山田錦＋季節副原料。",
        "features": "桜・抹茶・柚子など季節の副原料を駆使したどぶろくを提供。",
        "association": False,
    },
    {
        "slug": "tokyo-station",
        "name": "東京駅酒造場",
        "name_kana": "トウキョウエキシュゾウジョウ",
        "prefecture": "東京都",
        "city": "千代田区丸の内（東京駅エキナカ）",
        "region": "関東",
        "founded": "2020",
        "official_url": "https://www.tokyostation-sakebrewery.com/",
        "philosophy": "世界初の駅ナカ醸造所。フルーツどぶろくと共同醸造シリーズを展開。",
        "features": "運営はせがわ酒店。マンゴー・リンゴ・みかん・パイン・桃・ぶどう・ハニーレモンなど多彩なフルーツどぶろく。",
        "association": False,
    },
    {
        "slug": "iyasaka",
        "name": "弥栄醸造",
        "name_kana": "イヤサカジョウゾウ",
        "prefecture": "新潟県",
        "city": "柏崎市宮之下集落",
        "region": "中部",
        "founded": "2026",
        "official_url": "https://sakestreet.com/ja/media/pioneers-iyasaka-brewery-niigata",
        "philosophy": "米麹100%の「十割麹酒」で清酒規格にとらわれない新しい酒のかたちを提案。",
        "features": "2026年1月「その他の醸造酒」製造免許取得。副原料なしだが米麹のみで造るため清酒規格外。",
        "association": False,
    },
    {
        "slug": "sakenova",
        "name": "SAKENOVA BREWERY",
        "name_kana": "サケノヴァブルワリー",
        "prefecture": "新潟県",
        "city": "佐渡市加茂歌代",
        "region": "中部",
        "founded": "2025",
        "official_url": "https://sakenovabrewery.jp/",
        "philosophy": "佐渡から世界へ。輸出用清酒とクラフトサケのデュアル免許戦略。",
        "features": "佐渡産米とル レクチエ・黒イチジク・リンゴ・ミカン等を副原料に。",
        "association": False,
    },
    {
        "slug": "linne",
        "name": "LINNÉ",
        "name_kana": "リンネ",
        "prefecture": "京都府",
        "city": "京都市（活動拠点）／群馬県渋川市（法人登記）",
        "region": "関西",
        "founded": "2024",
        "official_url": "https://sakeworld.jp/sakebrewery/kyoto-linne/",
        "philosophy": "元WAKAZE杜氏・今井翔也創業。米以外の麹（大麦麹・蕎麦・芋麹）でつくる「800（ヤオ）」シリーズ。",
        "features": "haccoba・阿部酒造・LIBROMで委託醸造のファントムブリュワリー。2026年京都自社醸造所開設予定。",
        "association": False,
    },
    {
        "slug": "amanosato",
        "name": "天郷醸造所",
        "name_kana": "アマノサトジョウゾウジョ",
        "prefecture": "福岡県",
        "city": "田川郡福智町",
        "region": "九州",
        "founded": "2025",
        "official_url": "https://amanosato-sake.com/",
        "philosophy": "福岡県産山田錦と合鴨農法ヒノヒカリ、福智町産無農薬果物・ハーブで醸す「在る宵」。",
        "features": "九州・福智町を拠点とした新興クラフトサケ醸造所。",
        "association": False,
    },
    {
        "slug": "nomu",
        "name": "NOMU醸造所",
        "name_kana": "ノムジョウゾウジョ",
        "prefecture": "沖縄県",
        "city": "沖縄市（コザ一番街）",
        "region": "沖縄",
        "founded": "2025",
        "official_url": "https://www.instagram.com/nomu_okinawa/",
        "philosophy": "沖縄県内初の「その他の醸造酒製造免許」取得。西表島・恩納村産米と県産フルーツで醸す。",
        "features": "シークヮーサーなど沖縄の素材を使うクラフトサケ。木花之醸造所が技術協力。",
        "association": False,
    },
    {
        "slug": "salmon-brewery",
        "name": "鮭酒造",
        "name_kana": "サケシュゾウ",
        "prefecture": "千葉県",
        "city": "香取郡多古町",
        "region": "関東",
        "founded": "2024",
        "official_url": "https://salmonbre.official.ec/",
        "philosophy": "労働者協同組合方式で、多古米と副原料で「限りなく日本酒に近いクラフトサケ」を目指す。",
        "features": "生酛造り＋副原料の組合せで独自の路線。日経新聞・Sake Worldで「クラフトサケ」と明記。",
        "association": False,
    },
    {
        "slug": "tsuchiura",
        "name": "土浦醸造",
        "name_kana": "ツチウラジョウゾウ",
        "prefecture": "茨城県",
        "city": "土浦市",
        "region": "関東",
        "founded": "2026予定",
        "official_url": "https://www.sake-ibaraki.com/",
        "philosophy": "創業77年超の地酒店「佐藤酒店」がクラフトサケ事業を新設。茨城出身南部杜氏が醸造。",
        "features": "2026年春開業予定。茨城産米を主原料に。",
        "association": False,
    },
    {
        "slug": "hakutsuru-sakecraft",
        "name": "HAKUTSURU SAKE CRAFT",
        "name_kana": "ハクツルサケクラフト",
        "prefecture": "兵庫県",
        "city": "神戸市東灘区（白鶴酒造資料館内）",
        "region": "関西",
        "founded": "2024",
        "official_url": "https://www.hakutsuru.co.jp/sakecraft/",
        "philosophy": "白鶴酒造のマイクロブルワリー。「その他の醸造酒として米以外の原料を使うSAKE」に初挑戦。",
        "features": "No.4はホップ使用（米以外）、ロゼ色。各回非再現の一期一会型。",
        "association": False,
    },
    {
        "slug": "dejima-hosendo",
        "name": "でじま芳扇堂",
        "name_kana": "デジマホウセンドウ",
        "prefecture": "長崎県",
        "city": "長崎市出島町",
        "region": "九州",
        "founded": "2023",
        "official_url": "https://djm-hosendo.co.jp/",
        "philosophy": "九州初の都市型どぶろく醸造所。Brewery＋さけBar＋うつわGalleryの複合型。",
        "features": "出島町で季節のどぶろくを醸造。",
        "association": False,
    },
    {
        "slug": "cultiva",
        "name": "Cultiva糸島醸造所",
        "name_kana": "カルティバイトシマジョウゾウショ",
        "prefecture": "福岡県",
        "city": "糸島市加布里",
        "region": "九州",
        "founded": "2025",
        "official_url": "https://cultiva-sake.com/",
        "philosophy": "「米のテロワール」がコンセプト。日本各地の米品種ごとに個性を表現するどぶろく。生酛・木桶仕込み。",
        "features": "公式に「クラフトサケの醸造所」と明記。日本各地の米品種を品種別に醸し分ける珍しい蔵。",
        "association": False,
    },
]


def by_slug(slug):
    for b in BREWERIES:
        if b["slug"] == slug:
            return b
    return None


def by_region(region):
    return [b for b in BREWERIES if b["region"] == region]


REGIONS = ["北海道", "東北", "関東", "中部", "関西", "中国", "四国", "九州", "沖縄"]
