# -*- coding: utf-8 -*-
"""saketto / 銘柄データ (一次ソース確認版・2026-05-30)

- abv は度数(%), volume_ml は容量(ml)。公式非開示は None
- price は税込・参考価格(円)。"市場実勢" or 公式非開示は None で note に補記
- sub_ingredients は副原料リスト (米麹のみは ["米のみ"])
- 価格は2026/05/30確認時点
"""

BRANDS = {

    # ── 協会加盟9社 ──

    "ine-to-agave": [
        {"name": "稲とアガベ CRAFT series", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["アガベシロップ"], "price": 2500,
         "note": "ブランドの代名詞。白ブドウや白桃を思わせる柔らかな香り（参考は500ml火入れ版・特約店。公式は720ml）"},
        {"name": "花風（ぐるりこ®）", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 2775,
         "note": "西洋唐花草（ホップ）を副原料に使用"},
        {"name": "稲とジャスミン", "abv": None, "volume_ml": None,
         "sub_ingredients": ["ジャスミン茶葉"], "price": None,
         "note": "試し桶（実験酒）。度数・容量・価格は公式非開示"},
        {"name": "稲とハチミツ", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["ハチミツ"], "price": 3300,
         "note": "麹の糖と白麹の酸にトチの蜂蜜を融合した実験的な一本"},
        {"name": "稲とリンゴ SPECIAL EDITION", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["リンゴ"], "price": 2959, "note": "特別版"},
        {"name": "稲とブドウ SPECIAL EDITION", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["ブドウ"], "price": 2959, "note": "甲州ブドウ×米。日本酒とワインの中間"},
    ],

    "haccoba": [
        {"name": "はなうたホップス", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["ホップ"], "price": 2420,
         "note": "看板銘柄。「花酛」とクラフトビールのドライホッピングを融合"},
        {"name": "hanamoto bretta [kriek]", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["花酛", "ベルギービール製法"], "price": 2640,
         "note": "「花酛」とベルギービール製法の融合"},
        {"name": "zairai [森 forest]", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["地元在来植物"], "price": 2420,
         "note": "在来植物による地酒表現"},
        {"name": "kasu [sansho lemonade]", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["山椒", "レモネード"], "price": 2420,
         "note": "未利用資源によるアップサイクル"},
        {"name": "水を編む", "abv": None, "volume_ml": None,
         "sub_ingredients": [], "price": None,
         "note": "ドブロク製法「花酛」の復刻版。日本パッケージデザイン大賞2025銀賞"},
    ],

    "lagoon": [
        {"name": "翔空 HOP SAKE ほっぺ", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["ホップ（シトラ）"], "price": 2420,
         "note": "看板銘柄。柑橘香と爽快さを兼備"},
        {"name": "翔空 ニゴリのHOP SAKE ほっぺ", "abv": 15.5, "volume_ml": 720,
         "sub_ingredients": ["ホップ（シトラ）"], "price": 2420,
         "note": "ニゴリ仕様、約100本限定"},
        {"name": "翔空 酔いどれ洋梨2025-2026 槽搾り生", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["ル・レクチェ（洋梨）"], "price": 2420,
         "note": "新潟ブランド洋梨×純米香"},
        {"name": "翔空 酔いどれメロン2025 ドブロク", "abv": 12, "volume_ml": 500,
         "sub_ingredients": ["マスクメロン"], "price": 2310,
         "note": "千葉産高級メロン使用"},
        {"name": "翔空 酔いどれイチゴ2025 槽絞り生", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["越後姫（イチゴ）"], "price": 2310,
         "note": "新潟産イチゴ約200kg使用"},
        {"name": "翔空 SAKEマルゲリータ Unpressed", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["トマト", "バジル"], "price": 1980,
         "note": "ピザマルゲリータをイメージしたドブロク"},
        {"name": "翔空 自然栽培亀の尾どぶろく", "abv": 17, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2100,
         "note": "幻の米「亀ノ尾」100%使用、192本限定"},
    ],

    "librom": [
        {"name": "LIBROMモスコミュール", "abv": None, "volume_ml": None,
         "sub_ingredients": [], "price": 2860, "note": "度数・容量・副原料公式非開示"},
        {"name": "博多美人", "abv": None, "volume_ml": None,
         "sub_ingredients": [], "price": 2860, "note": "度数・容量・副原料公式非開示"},
        {"name": "TOMATO", "abv": None, "volume_ml": None,
         "sub_ingredients": ["トマト"], "price": 2860,
         "note": "度数・容量公式非開示"},
        {"name": "あまおうのおさけ", "abv": 4, "volume_ml": 500,
         "sub_ingredients": ["あまおう（福岡県産いちご）"], "price": 2750,
         "note": "福岡県産素材×クラフトサケ"},
        {"name": "FREROM Hallertau Blanc", "abv": 5, "volume_ml": 500,
         "sub_ingredients": ["ホップ（Hallertau Blanc）"], "price": 2860,
         "note": "ホップ品種Hallertau Blancを使った香り重視の一本"},
        {"name": "サワーコーラ", "abv": None, "volume_ml": None,
         "sub_ingredients": [], "price": 3300, "note": "副原料公式非開示"},
    ],

    "konohanano": [
        {"name": "ハナグモリ", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 1980,
         "note": "看板銘柄。本格純米にごり酒、シュワッとガス感"},
        {"name": "ハナグモリ THE酸", "abv": None, "volume_ml": 500,
         "sub_ingredients": [], "price": None,
         "note": "酸味を強調した派生銘柄"},
        {"name": "ハナグモリ 焼酎用白麹仕様", "abv": None, "volume_ml": None,
         "sub_ingredients": ["焼酎用白麹"], "price": None,
         "note": "バリエーション銘柄"},
    ],

    "happy-taro": [
        {"name": "ハッピーどぶろく 穂の恵み", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["米のみ（穂の恵み米）"], "price": 1870,
         "note": "定番どぶろく"},
        {"name": "ハッピーどぶろく 生もと 酵母無添加", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["米のみ"], "price": 2310,
         "note": "生もと造り、酵母無添加"},
        {"name": "ハッピーどぶろく ホップ Huell Melon", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["ホップ（Huell Melon）"], "price": 2310, "note": ""},
        {"name": "something happy うきうきホップ", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["ホップ"], "price": 2530, "note": ""},
        {"name": "something happy 菅浦の八朔", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["八朔"], "price": 2970, "note": ""},
        {"name": "something happy 政所と共に", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["茶葉（政所茶）"], "price": 2530, "note": ""},
        {"name": "something happy 音羽の黒文字", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["黒文字"], "price": 2970, "note": ""},
    ],

    "heiroku": [
        {"name": "Re:vive 久遠 misty おりがらみ", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["発芽玄米"], "price": None,
         "note": "発芽玄米ベースのRe:viveシリーズ標準"},
        {"name": "Re:vive 刹那", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["発芽玄米"], "price": 2200,
         "note": "特約店扱い・参考価格"},
        {"name": "Re:vive Origin アカツキ", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["発芽玄米"], "price": 11000,
         "note": "ハイエンド・特約店扱い参考価格"},
        {"name": "layer 洋ナシ", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["洋ナシ果汁"], "price": 2200, "note": "特約店扱い"},
        {"name": "layer ぶどう", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["ぶどう果汁"], "price": 2200, "note": "特約店扱い"},
        {"name": "layer りんご", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["りんご果汁"], "price": 2200, "note": "特約店扱い"},
    ],

    "pukupuku": [
        {"name": "#plot 酵母無添加 ホップサケ", "abv": 7, "volume_ml": None,
         "sub_ingredients": ["ホップ"], "price": None,
         "note": "低アルコールのホップサケ"},
        {"name": "VaVaVa Spring 2026 DDH Doburoku", "abv": None, "volume_ml": 660,
         "sub_ingredients": ["ホップ"], "price": 2640, "note": ""},
        {"name": "KiKiKi Spring 2026 Hopped Sour", "abv": None, "volume_ml": 660,
         "sub_ingredients": ["ホップ"], "price": 2530, "note": ""},
        {"name": "#wildpath 水もとホップどぶろく", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["ホップ"], "price": 2163, "note": ""},
        {"name": "#ODAKA 蔵付酵母 木桶どぶろく", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ"], "price": None,
         "note": "ICC SAKE AWARD 2025優勝銘柄"},
        {"name": "木桶発酵 全麹酒 雫取り", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["米のみ（全麹）"], "price": 11000,
         "note": "木桶仕込みの全麹酒、ハイエンド"},
        {"name": "アマーロどぶろく feat.伊勢屋酒造", "abv": None, "volume_ml": 460,
         "sub_ingredients": ["ハーブ（アマーロ粕由来）"], "price": 2750,
         "note": "他蔵コラボ"},
    ],

    "adachi-noujo": [
        {"name": "KOYOI ～la première année～", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ（白麹仕込み・精米歩合80%）"], "price": None,
         "note": "第一弾。スッキリした綺麗さと心地よい酸"},
        {"name": "KOYOI La deuxième", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": None, "note": "第二弾"},
    ],

    # ── 協会非加盟16社（Agent A 2026/05/30公式EC個別確認版） ──

    # nondo（岩手県遠野市）/ 「権化」シリーズ + 「とおの どぶろく」
    "nondo": [
        {"name": "権化 土の密℃", "abv": 14, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "水もと仕込み・木桶・150日超発酵。柑橘香と軽い甘み"},
        {"name": "権化 Rafters", "abv": 14, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "古民家梁を再利用した搾り機。シャープな酸"},
        {"name": "権化 MARO 無濾過生原酒", "abv": 12, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "水もと・木桶仕込み150日超の無濾過生原酒（公式525ml。720ml流通版もあり）"},
        {"name": "権化 MO CHUISLE", "abv": None, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "権化シリーズ。度数公式非開示"},
        {"name": "権化生酛", "abv": None, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "生酛仕込み版"},
        {"name": "とおの どぶろく 水もと無添加 生", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2750,
         "note": "水もと・無添加。要冷蔵"},
        {"name": "とおの どぶろく 生酛無添加 生", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2970, "note": "生酛・無添加"},
        {"name": "とおの どぶろく 速醸 生", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2750, "note": "速醸仕込み・生"},
        {"name": "とおの どぶろく 速醸火入れ", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2420, "note": "速醸火入れ"},
    ],

    # Fermenteria（宮城・仙台駅）
    "fermenteria": [
        {"name": "サケベイビー オリジナル", "abv": 5, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 3650,
         "note": "毎日仕込む駅ナカ生クラフトサケ。瓶90ml/600円も"},
        {"name": "サケベイビー シーズナル", "abv": None, "volume_ml": None,
         "sub_ingredients": ["季節素材"], "price": None,
         "note": "季節副原料入りバリエーション"},
        {"name": "サケベイビー エクスペリメンタル", "abv": None, "volume_ml": None,
         "sub_ingredients": [], "price": None,
         "note": "実験シリーズ。度数が5%超になることも"},
        {"name": "カボセットショコラ", "abv": 4, "volume_ml": 375,
         "sub_ingredients": ["カボス", "ココアパウダー", "蜂蜜"], "price": 2700,
         "note": "フランス菓子オランジェットを思わせる季節限定デザート酒。火入れ"},
    ],

    # やまね酒造（埼玉県飯能市）/ 副原料は「飯能産」が正（狭山茶は誤り）
    "yamane": [
        {"name": "やまねのみのり（茶Ver.）", "abv": None, "volume_ml": 300,
         "sub_ingredients": ["飯能産茶葉"], "price": 1500,
         "note": "全量袋吊り搾り。米・米麹に飯能産茶葉"},
        {"name": "やまねのみのり（蜂蜜Ver.）", "abv": None, "volume_ml": 300,
         "sub_ingredients": ["飯能産蜂蜜"], "price": 1500,
         "note": "全量袋吊り搾り。米・米麹に蜂蜜"},
        {"name": "やまねのみのり（発芽玄米Ver.）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["発芽玄米"], "price": None,
         "note": "公式に発芽玄米Verの言及あり。詳細仕様非開示"},
    ],

    # 平和どぶろく兜町醸造所（東京）/ 看板3副原料 + 本日のどぶろく
    "heiwa-kabutocho": [
        {"name": "平和どぶろく プレーン", "abv": None, "volume_ml": 70,
         "sub_ingredients": ["米のみ"], "price": 500,
         "note": "店内提供70ml/500円"},
        {"name": "平和どぶろく 小豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["小豆"], "price": None,
         "note": "看板副原料3種の一つ"},
        {"name": "平和どぶろく 黒豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["黒豆"], "price": None,
         "note": "看板副原料3種の一つ"},
        {"name": "平和どぶろく ホップ", "abv": None, "volume_ml": None,
         "sub_ingredients": ["ホップ"], "price": None,
         "note": "看板副原料3種の一つ"},
        {"name": "本日のどぶろく（生姜など）", "abv": None, "volume_ml": 70,
         "sub_ingredients": ["季節副原料"], "price": 550,
         "note": "店内日替り。生姜等"},
    ],

    # 平和どぶろく難波醸造所（大阪・なんば高島屋B1F）
    "heiwa-namba": [
        {"name": "どぶろく プレーン", "abv": None, "volume_ml": 70,
         "sub_ingredients": ["米のみ"], "price": 500,
         "note": "店内提供70ml/500円・120ml/950円"},
        {"name": "どぶろく 小豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["小豆"], "price": None, "note": "兜町と共通の看板副原料"},
        {"name": "どぶろく 黒豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["黒豆"], "price": None, "note": "兜町と共通の看板副原料"},
        {"name": "どぶろく ホップ", "abv": None, "volume_ml": None,
         "sub_ingredients": ["ホップ"], "price": None, "note": "兜町と共通の看板副原料"},
        {"name": "どぶろく 白麹", "abv": None, "volume_ml": None,
         "sub_ingredients": ["白麹（焼酎用）"], "price": None,
         "note": "焼酎用白麹仕込みで酸味強め"},
        {"name": "どぶろく 桜（季節限定）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["塩漬け桜葉"], "price": None,
         "note": "塩漬け桜葉を副原料に。春限定"},
        {"name": "どぶろく 抹茶（季節限定）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["抹茶"], "price": None, "note": "季節限定"},
    ],

    # 東京駅酒造場（東京駅エキナカ、はせがわ酒店）
    "tokyo-station": [
        {"name": "東京駅 どぶろく", "abv": 7, "volume_ml": 300,
         "sub_ingredients": ["米のみ"], "price": 1320,
         "note": "エキナカ初醸造。アルコール7%で軽快"},
        {"name": "季節のフルーツどぶろく マンゴー", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["マンゴー果汁"], "price": None,
         "note": "ヨーグルト風の酸+果実の甘み"},
        {"name": "季節のフルーツどぶろく リンゴ", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["リンゴ果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく ぶどう", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["ぶどう果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく 桃", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["桃果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく パイナップル", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["パイナップル果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく みかん", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["みかん果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく ハニーレモン", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["蜂蜜", "レモン"], "price": None, "note": "季節限定"},
    ],

    # 弥栄醸造（新潟）/ 阿部酒造委託でスタート
    "iyasaka": [
        {"name": "ITTEKI（一擲）十割麹酒 Vol.0-1", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ（米麹100%）"], "price": None,
         "note": "新潟県柏崎市宮之下産コシヒカリ100%。阿部酒造委託醸造。米麹のみのため清酒規格外"},
    ],

    # SAKENOVA BREWERY（新潟・佐渡）/ Crafted Series -Brew Note- が自社醸造
    "sakenova": [
        {"name": "Brew Note 001 HONEY", "abv": None, "volume_ml": None,
         "sub_ingredients": ["蜂蜜"], "price": None,
         "note": "離島初クラフトサケ醸造所の初リリース（2025/12/21）"},
        {"name": "Brew Note 002 APPLE & MIKAN", "abv": 12.5, "volume_ml": 720,
         "sub_ingredients": ["佐渡産りんご果汁", "佐渡産みかん果汁"], "price": 3300,
         "note": "麹米山田錦・掛米こしいぶき・精米60%。日本酒度-8.57"},
        {"name": "Brew Note 006 Strawberry", "abv": 12.5, "volume_ml": 720,
         "sub_ingredients": ["佐渡産いちご「越後姫」"], "price": 2750,
         "note": "精米歩合60%。日本酒度-5.93"},
    ],

    # LINNÉ（京都拠点・委託醸造）
    "linne": [
        {"name": "800 大麦", "abv": 16, "volume_ml": 500,
         "sub_ingredients": ["大麦麹"], "price": 3850,
         "note": "haccoba委託醸造。COEDO BREWERY川越産大麦+福島米。ICC SAKE AWARD 2025準優勝"},
        {"name": "800 蕎麦", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["蕎麦麹"], "price": None,
         "note": "阿部酒造委託醸造（新潟）"},
        {"name": "800 米", "abv": 16, "volume_ml": 500,
         "sub_ingredients": ["米麹のみ"], "price": None,
         "note": "阿部酒造委託醸造。米麹100%のため清酒規格外"},
    ],

    # 天郷醸造所（福岡・福智町）/ フルーツSAKE系。副原料=ミント/苺/レモン（旧「米のみ」表記は誤り。2026-05-31公式オンラインショップで再確認）
    "amanosato": [
        {"name": "在る 緒奏（しょそう）720ml", "abv": 16, "volume_ml": 720,
         "sub_ingredients": ["ミント"], "price": 2640,
         "note": "火入れ版¥2,640/おりがらみ生原酒版¥2,750。福岡県産山田錦100%。ふるさと納税出品あり。「ほんのりミント香る」（公式商品名）"},
        {"name": "在る 小暖（こはる）500ml", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["あまおう苺"], "price": 3850,
         "note": "春限定。福智町産あまおう苺の甘み・酸味・香り"},
        {"name": "在る 寒夜（かんや）500ml", "abv": 16, "volume_ml": 500,
         "sub_ingredients": ["レモン"], "price": 2860,
         "note": "原材料: 米(福岡産)・米麹(福岡産)・レモン(福智町産)。生酒/おりがらみ生原酒の2種"},
    ],

    # NOMU醸造所（沖縄・コザ）
    "nomu": [
        {"name": "シシカム", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ"], "price": 1800,
         "note": "肉に合う甘酸ニゴリ。500ml/720ml/1800ml展開"},
        {"name": "OFFZAKE（ノンアル甘酒）", "abv": 0, "volume_ml": None,
         "sub_ingredients": ["白麹", "沖縄県産米"], "price": 3150,
         "note": "ノンアル甘酒。プレーン/パイン/島ソルト/黒糖の4種"},
        {"name": "NOMU（クラフトサケ）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["シークヮーサー（予定）"], "price": None,
         "note": "コアライン。シークヮーサー副原料の予定"},
        {"name": "TABERU（食べる酒）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ"], "price": 1980,
         "note": "無濾過の濃厚どぶろく"},
    ],

    # 鮭酒造（千葉・多古）
    "salmon-brewery": [
        {"name": "生酛純米酒 鮭（第1弾）", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": None,
         "note": "千葉県多古町産中生神力（合鴨農法）。精米歩合90%・生酛・無濾過原酒・瓶燗一度火入れ・おりがらみ。43日発酵"},
    ],

    # 土浦醸造（茨城）/ 2026春オープン、銘柄未発表
    "tsuchiura": [],

    # HAKUTSURU SAKE CRAFT（兵庫神戸・白鶴資料館限定）
    "hakutsuru-sakecraft": [
        {"name": "HAKUTSURU SAKE CRAFT No.1", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 4400,
         "note": "白鶴錦100%・精米50%・純米大吟醸。パイン香"},
        {"name": "HAKUTSURU SAKE CRAFT No.2", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 5500,
         "note": "純米大吟醸・酵母2種ブレンド。パインとメロン香。220本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.3", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 7700,
         "note": "全国新酒鑑評会出品仕様"},
        {"name": "HAKUTSURU SAKE CRAFT No.4", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 6050,
         "note": "白鶴錦100%・純米大吟醸ベース+ホップ。ロゼ色。208本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.5", "abv": 16, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": None,
         "note": "白鶴錦100%・精米38%・大吟醸。リンゴ香と上品な甘み"},
        {"name": "HAKUTSURU SAKE CRAFT No.6", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["神戸産いちご「あきひめ」"], "price": None,
         "note": "純米大吟醸ベース+神戸産いちご。229本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.7", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": None, "note": "216本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.15", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["ハーブ"], "price": None,
         "note": "醸造所発酵CO2を循環活用したハーブ香SAKE"},
        {"name": "HAKUTSURU SAKE CRAFT THE PREMIUM 2026", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 111100,
         "note": "白鶴錦100%・精米38%・純米大吟醸。64本限定"},
    ],

    # でじま芳扇堂（長崎・出島）/ 雲・波・友 シリーズ
    "dejima-hosendo": [
        {"name": "芳扇 雲 1st", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 2750,
         "note": "精米92%・白麹仕込み・一度火入れ。ムース状のテクスチャ"},
        {"name": "芳扇 紫雲", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["雲仙市産黒米（古代米）"], "price": 6600,
         "note": "古代黒米使用の紫色どぶろく。250本限定"},
        {"name": "芳扇 吟雲", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 4180,
         "note": "雲シリーズ上位。Tokyo酒チャレンジ2025金賞"},
        {"name": "芳扇 桜雲", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3850, "note": "雲シリーズ"},
        {"name": "芳扇 雷雲", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "雲シリーズ"},
        {"name": "芳扇 波 1st", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 2750,
         "note": "精米80%・岡山県倉敷産雄町・一度火入れ"},
        {"name": "芳扇 友 内田米レイホウ 菩提酛仕込", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300,
         "note": "熊本県阿蘇内田農園レイホウ精米70%・菩提酛"},
        {"name": "芳扇 友 内田米美山錦", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3520, "note": "内田農園美山錦"},
        {"name": "芳扇 友 目黒米雄町", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "目黒農園雄町"},
        {"name": "芳扇 波 内田米レイホウ 菩提酛仕込", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "波シリーズ・菩提酛版"},
        {"name": "芳扇 波 内田米美山錦", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3520, "note": "波シリーズ"},
        {"name": "芳扇 波 目黒米雄町", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "波シリーズ"},
        {"name": "芳扇 波 ピンクラベル", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "波シリーズ"},
    ],

    # Cultiva糸島醸造所（福岡・糸島）/ 米のテロワール
    "cultiva": [
        {"name": "Sankeinishiki NAGANO 2025BY", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ（山恵錦・長野県産）"], "price": None,
         "note": "長野県産山恵錦で醸す品種別どぶろく。生酛・木桶仕込み"},
        {"name": "Hinohikari FUKUOKA 2025BY", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ（ヒノヒカリ・福岡県産）"], "price": None,
         "note": "福岡県産ヒノヒカリで醸す品種別どぶろく"},
        {"name": "Yamadanishiki FUKUOKA 2025BY", "abv": None, "volume_ml": None,
         "sub_ingredients": ["米のみ（山田錦・福岡県産）"], "price": None,
         "note": "福岡県産山田錦で醸す品種別どぶろく"},
    ],
}


def for_brewery(slug):
    return BRANDS.get(slug, [])
