# -*- coding: utf-8 -*-
"""saketto / 銘柄データ (一次ソース確認版・2026-05-30)

- abv は度数(%), volume_ml は容量(ml)。公式非開示は None
- price は税込・参考価格(円)。"市場実勢" or 公式非開示は None で note に補記
- sub_ingredients は副原料リスト (米麹のみは ["米のみ"])
- 価格は2026/05/30確認時点
"""

BRANDS = {

    # ── 協会加盟9社 ──

    "ine-to-agave": [
        {"name": "稲とアガベ", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["アガベシロップ"], "price": 2500,
         "note": "ブランドの代名詞。白ブドウや白桃を思わせる柔らかな香り（参考は500ml火入れ版・特約店。公式は720ml）"},
        {"name": "花風（ぐるりこ®）", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 2790,
         "note": "西洋唐花草（ホップ）を副原料に使用"},
        {"name": "稲とジャスミン", "abv": None, "volume_ml": None,
         "sub_ingredients": ["ジャスミン茶葉"], "price": None,
         "note": "試し桶（実験酒）。度数・容量・価格は公式非開示"},
        {"name": "稲とハチミツ", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["ハチミツ"], "price": 3300,
         "note": "麹の糖と白麹の酸にトチの蜂蜜を融合した実験的な一本"},
        {"name": "稲とリンゴ", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["リンゴ（紅の夢）"], "price": 2959,
         "note": "秋田県横手市産『紅の夢』（果肉まで赤く酸味が特徴）を米・米麹と発酵。精米歩合90%"},
        {"name": "稲とブドウ", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["ブドウ（甲州）"], "price": 2959,
         "note": "甲州ブドウ×米。日本酒とワインの中間。精米歩合90%"},
        # ── 2026/08/09 公式オンラインショップ(shop.inetoagave.com)で確認して追加 ──
        {"name": "稲とリンゴ SPECIAL EDITION", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["リンゴ（紅の夢）"], "price": 7150,
         "note": "公式が「稲とアガベ最高峰のクラフトサケ」と位置づける720ml版。紅の夢を米・麹と発酵・熟成。精米歩合90%"},
        {"name": "稲とブドウ SPECIAL EDITION 2024", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["ブドウ（甲州）"], "price": 7150,
         "note": "通常版（500ml）とは別SKUの720ml最高峰シリーズ。精米歩合90%"},
        {"name": "交酒 花風", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 2420,
         "note": "公式表記の原材料は米・米麹・ホップ。ライチやマスカットを思わせる風味。精米歩合90%"},
        {"name": "交酒花風（6号酵母）", "abv": None, "volume_ml": 720,
         "sub_ingredients": None, "price": 2750,
         "note": "秋田生まれの協会6号酵母を使用した花風。精米歩合90%。原材料は公式非開示"},
        {"name": "火折", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["青文字の実", "榧（かや）の枝葉", "花蓬", "アオノクマタケランの葉"], "price": 3850,
         "note": "日本草木研究所とのコラボ。4種のボタニカルを使用。精米歩合90%"},
        {"name": "廻", "abv": None, "volume_ml": 720,
         "sub_ingredients": ["クラフトジンのボタニカル残渣"], "price": 3850,
         "note": "自社・早苗饗蒸留所のジン製造で出たボタニカル残渣を米・麹と仕込む。原料と副産物が廻り続けることから命名。精米歩合90%"},
        {"name": "DOBUROKU ホップ", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["ホップ"], "price": 2695,
         "note": "米・麹・ホップの定番どぶろく。年1回のみの仕込みで酸味を高めた設計。精米歩合90%"},
        {"name": "稲とブドウとホップ", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["ブドウ", "ホップ"], "price": 2950,
         "note": "日本酒とワインとビールを掛け合わせたクラフトサケ。ホップのポリフェノールでロゼワインのような色合いに。精米歩合90%"},
        {"name": "SAKE 稲とアガベ×土田酒造", "abv": None, "volume_ml": 720,
         "sub_ingredients": None, "price": 3300,
         "note": "群馬・土田酒造で醸造したコラボ。精米歩合90%。原材料は公式非開示"},
        {"name": "稲とアガベと谷泉", "abv": None, "volume_ml": None,
         "sub_ingredients": ["ブルーベリー"], "price": None,
         "note": "能登半島地震で全壊被害を受けた鶴野酒造店（谷泉）との共同醸造。「能登の酒を止めるな！」プロジェクト。度数・容量・価格は公式非開示"},
    ],

    "haccoba": [
        {"name": "はなうたホップス", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 2420,
         "note": "看板銘柄。「花酛」とクラフトビールのドライホッピングを融合"},
        {"name": "hanamoto bretta [kriek]", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["花酛", "ベルギービール製法"], "price": 2640,
         "note": "「花酛」とベルギービール製法の融合"},
        {"name": "zairai [森 forest]", "abv": 11, "volume_ml": 500,
         "sub_ingredients": ["地元在来植物"], "price": 2420,
         "note": "在来植物による地酒表現"},
        {"name": "kasu [sansho lemonade]", "abv": 10, "volume_ml": 500,
         "sub_ingredients": ["山椒", "レモネード"], "price": 2420,
         "note": "未利用資源によるアップサイクル"},
        {"name": "水を編む", "abv": 13, "volume_ml": 500,
         "sub_ingredients": [], "price": 2860,
         "note": "ドブロク製法「花酛」の復刻版。日本パッケージデザイン大賞2025銀賞"},
    ],

    "lagoon": [
        {"name": "翔空 HOP SAKE ほっぺ", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["ホップ（シトラ）"], "price": 2420,
         "note": "看板銘柄。柑橘香と爽快さを兼備"},
        {"name": "翔空 ニゴリのHOP SAKE ほっぺ", "abv": 15.5, "volume_ml": 720,
         "sub_ingredients": ["ホップ（シトラ）"], "price": 2420,
         "note": "ニゴリ仕様、約100本限定"},
        {"name": "翔空 酔いどれ洋梨2025-2026 槽搾り生", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["ル・レクチェ（洋梨）"], "price": 2420,
         "note": "新潟ブランド洋梨×純米香"},
        {"name": "翔空 酔いどれメロン2025 ドブロク", "abv": 12, "volume_ml": 500,
         "sub_ingredients": ["マスクメロン"], "price": 2310,
         "note": "千葉産高級メロン使用"},
        {"name": "翔空 酔いどれイチゴ2026 槽絞り生", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["越後姫（イチゴ）"], "price": 2420,
         "note": "新潟のブランドイチゴ「越後姫」を米の量に対して約60%使用。香料・甘味料は不使用。日本酒度-9／酸度3.5。酒母は高温糖化、麹は黄麹。2026/08/31に公式現行の2026年版へ更新（旧2025表記・¥2,310から）"},
        {"name": "翔空 SAKEマルゲリータ Unpressed", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["トマト", "バジル"], "price": 1980,
         "note": "ピザマルゲリータをイメージしたドブロク"},
        {"name": "翔空 自然栽培亀の尾どぶろく", "abv": 17, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2100,
         "note": "幻の米「亀ノ尾」100%使用、192本限定"},
        # ── 2026/08/09 公式オンラインショップ(BASE)で確認して追加 ──
        {"name": "翔空 微発泡の HOP SAKE ほっぺ", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["ホップ（シトラ）"], "price": 2530,
         "note": "搾ったあとにオリを絡め、ビン内二次発酵で発泡性をもたせたうすにごり。蔵初の品目【発泡酒】製品。原料米は新潟市北区産五百万石100%。度数はロットで変動（公式現行R616は15度）"},
        # ── 2026/08/31 公式オンラインショップで確認して追加 ──
        {"name": "翔空 森のSAKE クロモジ", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["クロモジ"], "price": 2310,
         "note": "新潟・栃尾地区の森で採取した香木クロモジをモロミで醸した槽搾り。酒母は高温糖化。原料米は新潟市北区産の五百万石・こしいぶき、精米歩合70%。2026/08/31時点で在庫なし"},
        {"name": "翔空 Hopped酔いどれメロン", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["メロン", "ホップ"], "price": 1980,
         "note": "『酔いどれメロン』にホップを絡めて搾った薄にごり。代表の出身地・千葉県大網白里産のマスクメロンとコシヒカリを使う。酒母は高温糖化、麹は黄麹。2026/08/31時点で在庫なし"},
        {"name": "レゾネコ 梅と茶 〜プロトタイプ〜", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["梅", "茶"], "price": 2530,
         "note": "麒麟山酒造の梅酒製造後の梅の実と、冨士美園の茶抽出後の茶殻をアップサイクルしたコラボ酒。麹は白麹（爽明）、酒母は高温糖化。抽選販売で2026/08/31時点は応募終了"},
        {"name": "翔空 酔いどれイチゴ2026 ドブロク", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["イチゴ"], "price": 2420,
         "note": "『酔いどれイチゴ』の未搾り版。槽絞り生とは別商品として公式が併売する。日本酒度-16.5／酸度3.1、酒母は高温糖化"},
    ],

    "librom": [
        {"name": "LIBROMモスコミュール", "abv": 11, "volume_ml": 500,
         "sub_ingredients": [], "price": 2860, "note": "度数・容量・副原料公式非開示"},
        {"name": "博多美人", "abv": 11, "volume_ml": 500,
         "sub_ingredients": [], "price": 2860, "note": "度数・容量・副原料公式非開示"},
        {"name": "TOMATO", "abv": 12, "volume_ml": 500,
         "sub_ingredients": ["トマト"], "price": 2860,
         "note": "度数・容量公式非開示"},
        {"name": "あまおうのおさけ", "abv": 4, "volume_ml": 500,
         "sub_ingredients": ["あまおう（福岡県産いちご）"], "price": 2750,
         "note": "福岡県産素材×クラフトサケ"},
        {"name": "FREROM Hallertau Blanc", "abv": 5, "volume_ml": 500,
         "sub_ingredients": ["ホップ（Hallertau Blanc）"], "price": 2860,
         "note": "ホップ品種Hallertau Blancを使った香り重視の一本"},
        {"name": "サワーコーラ", "abv": 10, "volume_ml": 500,
         "sub_ingredients": [], "price": 3300, "note": "副原料公式非開示"},
    ],

    "konohanano": [
        {"name": "ハナグモリ", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2178,
         "note": "看板銘柄。品目は「濁酒」。磨かないお米を使うため栄養価も高いと公式が説明する。2026/08/31に公式ストアの税込価格2,178円へ修正（旧登録は税抜1,980円で、他銘柄の税込表記と揃っていなかった）"},
        {"name": "ハナグモリ THE酸", "abv": 12, "volume_ml": 500,
         "sub_ingredients": [], "price": 1980,
         "note": "酸味を強調した派生銘柄"},
        {"name": "ハナグモリ 焼酎用白麹仕様", "abv": 12, "volume_ml": 500,
         "sub_ingredients": ["焼酎用白麹"], "price": 1980,
         "note": "バリエーション銘柄"},
        # ── 2026/08/09 公式オンラインストアで確認して追加 ──
        {"name": "EVAN-GARDE 「木花之醸造所×初号機」", "abv": 13, "volume_ml": None,
         "sub_ingredients": ["黒米", "ホップ", "エルダーフラワー"], "price": 3200,
         "note": "エヴァンゲリオン初号機をイメージし、黒米とホップ由来の紫色に仕上げたコラボ品。品目は「その他醸造酒」。精米歩合90%・701号酵母。容量は公式に記載なし"},
        # ── 2026/08/31 公式オンラインストアで確認して追加 ──
        {"name": "HAZY SAKE", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["ホップ（Sabro）", "ハイビスカス", "レモングラス"], "price": 2400,
         "note": "蔵の定番ホップどぶろく。エール酵母を使い米をしっかり溶かしたなめらかな質感に、白麹とホップの上立ち香。仕上げにハーブを加えて後味を軽くしている"},
        {"name": "ストロベリーショコラ 濁酒", "abv": 8, "volume_ml": 500,
         "sub_ingredients": ["いちごピューレ", "カカオニブ"], "price": 2500,
         "note": "カカオニブといちごピューレを使うデザート系どぶろく。公式は熱燗での飲み方も勧めている"},
        {"name": "YEAH「アサイーSAKE」〜立正大学×木花之醸造所〜", "abv": 5, "volume_ml": 350,
         "sub_ingredients": ["アサイーピューレ", "バナナ", "イチゴ", "ブルーベリー", "ラズベリー", "クランベリー", "蜂蜜"], "price": 1800,
         "note": "立正大学経営学部・藤井ゼミとのコラボ。仕込みに乳酸を入れヨーグルトのような甘酸っぱさに、ベリーは粗く砕いて食感を残す。原材料に蜂蜜を含むが公式に品目の記載はない。2026/08/31時点で在庫なし"},
        {"name": "Snow Dome【スノードーム】", "abv": 12, "volume_ml": None,
         "sub_ingredients": ["ラズベリーピューレ", "カシスピューレ", "クランベリーシロップ"], "price": 2700,
         "note": "醸造スタッフ「ねね」による「ねねRock」シリーズ第2弾。赤米・黒米の古代米に洋のベリーを合わせる。振ると滓とラメが雪のように舞う。容量は公式に記載なし"},
        {"name": "大人のネクター03「ネクタリン」", "abv": 9, "volume_ml": None,
         "sub_ingredients": ["ネクタリン（福島県産）"], "price": 2500,
         "note": "「大人のネクター」シリーズ第3弾。福島市ABE果樹園のネクタリンを皮ごと使用。酸味を引き立てるため白麹を通常より多くしている。精米歩合90%。容量は公式に記載なし"},
        {"name": "Daiginjo Method", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["ウッドチップ（桜）"], "price": 3500,
         "note": "純米大吟醸の製造法に沿って造りつつ、台東区の区花である桜のウッドチップを使うため品目は「その他醸造酒」と公式が明記。岡山県産山田錦100%・精米歩合50%、きょうかい701号70%と901号30%。醸造年度R7BY"},
        {"name": "ジャスミン 濁酒ver.", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["ジャスミン"], "price": 2400,
         "note": "米とジャスミンだけで造る一本の濁酒版。ミルキーな味わいで、香りは軽く甘く優しい。澄酒ver.とは同じ仕込みの搾り分けだが公式ストアでは別商品として販売"},
        {"name": "ジャスミン 澄酒ver.", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["ジャスミン"], "price": 2400,
         "note": "濁酒ver.と同じ仕込みを搾った澄酒版。ジャスミンの爽やかな香りがしっかり感じられ、甘さ控えめでエレガントな仕上がり"},
        {"name": "LAB02「出汁パンチ」", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["かつお節", "梅干し"], "price": 2400,
         "note": "3代目醸造長・木村によるLABシリーズ。鰹節を煮出して仕込み水にし、発酵後期に梅干しを入れて塩味と酸味を足す。江戸時代の調味料「煎り酒」の製法がヒント。テーマは「ぼくのかんがえたさいきょうのあつかん」"},
        {"name": "栗熟成酒「ヘーゼルナッツショコラ」〜bitter taste〜", "abv": 12, "volume_ml": 500,
         "sub_ingredients": ["ヘーゼルナッツペースト", "ココアパウダー", "バニラビーンズ"], "price": 3000,
         "note": "もち米シリーズ第2弾。栗の木の樽でどぶろくを半年熟成させ、ヘーゼルナッツとカカオ、バニラを加えてもち米の濃厚な醪と合わせる。品目は公式に「その他醸造酒」と明記。温めて飲むことを公式が勧める"},
        {"name": "ミードブロク", "abv": 11, "volume_ml": 500,
         "sub_ingredients": ["はちみつ（国産）"], "price": 2500,
         "note": "ミード（蜂蜜酒）と日本酒の製造技術を融合させたフュージョンSAKE。上野エリアで養蜂されたハチミツを使い荒漉しで仕上げ、半年ほど熟成させる。公式に品目の記載はない"},
        {"name": "passionfruit sake [bartender waka collaboration]", "abv": 7, "volume_ml": 500,
         "sub_ingredients": ["パッションフルーツピューレ", "ブドウ果汁（ソーヴィニヨンブラン）", "茶葉（ラフランス茶）"], "price": 2500,
         "note": "麻布十番のバーテンダーWAKA氏のレシピによるコラボ。濁酒をベースにパッションフルーツと白ワイン用ぶどうジュース、ラフランス茶を合わせる。公式は「クラフトサケ」「濁酒」と表現するが品目の記載はなく、果汁と上白糖を発酵中に入れるのか後から加えるのかも公式からは判別できない"},
    ],

    "happy-taro": [
        {"name": "ハッピーどぶろく 穂の恵み", "abv": 12, "volume_ml": 480,
         "sub_ingredients": ["米のみ（穂の恵み米）"], "price": 1870,
         "note": "定番どぶろく"},
        {"name": "ハッピーどぶろく 生もと 酵母無添加", "abv": 12, "volume_ml": 480,
         "sub_ingredients": ["米のみ"], "price": 2310,
         "note": "生もと造り、酵母無添加"},
        {"name": "ハッピーどぶろく ホップ Huell Melon", "abv": 13, "volume_ml": 480,
         "sub_ingredients": ["ホップ（Huell Melon）"], "price": 2310, "note": ""},
        {"name": "something happy うきうきホップ", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["ホップ"], "price": 2530, "note": ""},
        {"name": "something happy 菅浦の八朔", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["八朔"], "price": 2970, "note": ""},
        {"name": "something happy 政所の茶縁", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["茶葉（政所茶）"], "price": 2530,
         "note": "公式現行表記は「政所の茶縁」（旧「政所と共に」から改称・2026/08/09公式で確認）"},
        {"name": "something happy 音羽の黒文字", "abv": 7, "volume_ml": 480,
         "sub_ingredients": ["黒文字"], "price": 2970, "note": ""},
        # ── 2026/08/09 公式サイト・公式ショップ(BASE)で確認して追加 ──
        {"name": "something happy オリエンタルホエイ", "abv": 8, "volume_ml": 480,
         "sub_ingredients": ["ホエー", "ローズペタル", "グリーンカルダモン", "ブラックペッパー", "ドライジンジャー"],
         "price": 2750,
         "note": "同じ建物「湖のスコーレ」のチーズ製造で出るホエイにスパイスを合わせたどぶろく。シタール奏者・石濱匡雄がスパイス監修。公式サイトの度数表記は5〜7%、現行ロット裏ラベルは8%"},
        {"name": "something happy フレッシュハーブティー", "abv": 7, "volume_ml": 480,
         "sub_ingredients": ["アップルミント", "日本ハッカ"], "price": 2970,
         "note": "広島・梶谷農園の季節のフレッシュハーブで淹れたハーブティーを仕込水に使用。2022年夏から続くフラッグシップ。公式サイトの度数表記は5〜8%、2026年ロット裏ラベルは7%"},
        {"name": "something happy 八朔 BITTER 2026", "abv": 9, "volume_ml": 480,
         "sub_ingredients": ["八朔"], "price": 2970,
         "note": "菅浦の八朔の今期初登場BITTER版。種由来の苦味を多めに抽出し3か月熟成。冬の商品を夏向けに仕立てた一本"},
        # ── 2026/08/31 公式サイト・公式ショップ(BASE)で確認して追加 ──
        {"name": "something happy 苺屋はな", "abv": None, "volume_ml": 480,
         "sub_ingredients": ["苺"], "price": None,
         "note": "滋賀県野洲市の苺農家「苺屋はな」の苺を使う季節限定品。生食出荷が難しい苺も買い取り全量を活用する。公式の度数表記は5〜8%の幅表記のため単一値は未記載。2026/08/31時点で公式ショップに出品なし"},
        {"name": "something happy MAROUのカカオ", "abv": 9, "volume_ml": 480,
         "sub_ingredients": ["カカオパウダー", "カカオニブ"], "price": None,
         "note": "ベトナムのビーンtoバー・チョコレートメーカーMAROUのカカオを使用。公式は「カカオは発酵食品」と説明する。2026/08/31時点で公式ショップに出品なし"},
        {"name": "やまのかみさん 大原の赤紫蘇", "abv": 7, "volume_ml": 480,
         "sub_ingredients": ["赤紫蘇"], "price": 2970,
         "note": "京都・大原の赤紫蘇を使う夏季どぶろく。公式説明に「全糀仕込み」と明記され、原材料も米麹と赤紫蘇のみで掛米の記載がない。原料米は自然栽培米（滋賀旭・ありがとう米・亀の尾4号）。品目は「その他の醸造酒」"},
        {"name": "ハッピーどぶろく 湖北はみ出し米", "abv": 13, "volume_ml": 480,
         "sub_ingredients": ["米のみ"], "price": 2110,
         "note": "虫がついたり割れたりして出荷されない小さな「はみ出し米」を主原料にした一本。酒母はクエン酸糀甘酒酛（乳酸不使用）。蔵のどぶろくの中で唯一日本酒らしい味わいと公式が説明する"},
    ],

    "heiroku": [
        {"name": "Re:vive 久遠 misty おりがらみ", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["発芽玄米"], "price": 2200,
         "note": "発芽玄米ベースのRe:viveシリーズ標準"},
        {"name": "Re:vive 刹那", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["発芽玄米"], "price": 2200,
         "note": "特約店扱い・参考価格"},
        {"name": "Re:vive Origin アカツキ", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["発芽玄米"], "price": 11000,
         "note": "ハイエンド・特約店扱い参考価格"},
        {"name": "layer 洋ナシ", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["洋ナシ果汁"], "price": 2200, "note": "特約店扱い"},
        {"name": "layer ぶどう", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["ぶどう果汁"], "price": 2530, "note": "特約店扱い"},
        {"name": "layer りんご", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["りんご果汁"], "price": 2530, "note": "特約店扱い"},
    ],

    "pukupuku": [
        {"name": "#plot 酵母無添加 ホップサケ", "abv": 7, "volume_ml": 500,
         "sub_ingredients": ["ホップ"], "price": 2054,
         "note": "低アルコールのホップサケ"},
        {"name": "VaVaVa Spring 2026 DDH Doburoku", "abv": None, "volume_ml": 660,
         "sub_ingredients": ["ホップ"], "price": 2640, "note": ""},
        {"name": "KiKiKi Spring 2026 Hopped Sour", "abv": 7, "volume_ml": 660,
         "sub_ingredients": ["ホップ"], "price": 2530, "note": ""},
        {"name": "#wildpath 水もとホップどぶろく", "abv": 7, "volume_ml": 500,
         "sub_ingredients": ["ホップ"], "price": 2163, "note": ""},
        {"name": "#ODAKA 蔵付酵母 木桶どぶろく", "abv": 7, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 1760,
         "note": "ICC SAKE AWARD 2025優勝銘柄"},
        {"name": "木桶発酵 全麹酒 雫取り", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["米のみ（全麹）"], "price": 11000,
         "note": "木桶仕込みの全麹酒、ハイエンド"},
        {"name": "アマーロどぶろく feat.伊勢屋酒造", "abv": 7, "volume_ml": 460,
         "sub_ingredients": ["ハーブ（アマーロ粕由来）"], "price": 2640,
         "note": "他蔵コラボ"},
    ],

    "adachi-noujo": [
        {"name": "KOYOI ～la première année～", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ（白麹仕込み・精米歩合80%）"], "price": 3960,
         "note": "第一弾。スッキリした綺麗さと心地よい酸"},
        {"name": "KOYOI La deuxième", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3960, "note": "第二弾"},
        # ── 2026/08/09 公式サイト・公式ショップで確認して追加（MIYOIは自社醸造所の主力ブランド。KOYOIは委託醸造の第一弾で品目=清酒） ──
        {"name": "MIYOI(美酔) -ライチ- 生 720ml", "abv": 12, "volume_ml": 720,
         "sub_ingredients": ["ライチ果汁"], "price": 2420,
         "note": "公式ショップが「足立農醸の唯一の定番商品」と記載。日本酒の発酵途中でライチを共発酵。原材料は米・米麹・ライチ果汁。搾り月でサブタイトルが変わる"},
        {"name": "MIYOI -旨すぎて御燗弁。- 燗酒専用酒 720ml", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["出汁（かつお節）", "出汁（昆布）"], "price": 2530,
         "note": "昆布と鰹節の特製出汁を醪へ仕込んだ燗酒専用クラフトサケ。公式推奨温度は50〜60度"},
    ],

    # ── 協会非加盟16社（Agent A 2026/05/30公式EC個別確認版） ──

    # nondo（岩手県遠野市）/ 「権化」シリーズ + 「とおの どぶろく」
    "nondo": [
        {"name": "権化 土の密℃", "abv": 14, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "水もと仕込み・木桶・150日超発酵。柑橘香と軽い甘み"},
        {"name": "権化 Rafters", "abv": 14, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "古民家梁を再利用した搾り機。シャープな酸"},
        {"name": "権化 MARO 無濾過生原酒", "abv": 12, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "水もと・木桶仕込み150日超の無濾過生原酒（公式525ml。720ml流通版もあり）"},
        {"name": "権化 MO CHUISLE", "abv": 12, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "権化シリーズ。度数公式非開示"},
        {"name": "権化生酛", "abv": 13, "volume_ml": 525,
         "sub_ingredients": ["米のみ（米糠活用）"], "price": 4950,
         "note": "生酛仕込み版"},
        {"name": "とおの どぶろく 水もと無添加 生", "abv": 9, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2750,
         "note": "水もと・無添加。要冷蔵"},
        {"name": "とおの どぶろく 生酛無添加 生", "abv": "10〜12", "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2970, "note": "生酛・無添加"},
        {"name": "とおの どぶろく 速醸 生", "abv": "10〜12", "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2750, "note": "速醸仕込み・生"},
        {"name": "とおの どぶろく 速醸火入れ", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 2420, "note": "速醸火入れ"},
    ],

    # Fermenteria（宮城・仙台駅）
    "fermenteria": [
        {"name": "サケベイビー オリジナル", "abv": 5.5, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 3650,
         "note": "仙台駅ナカの8Lタンクで毎日仕込むスタイルの生クラフトサケ。もろみ10日。90ml瓶(600円)もあり"},
        {"name": "サケベイビー シーズナル", "abv": 5, "volume_ml": 500,
         "sub_ingredients": ["季節素材"], "price": None,
         "note": "季節副原料入りバリエーション"},
        {"name": "サケベイビー エクスペリメンタル", "abv": None, "volume_ml": 500,
         "sub_ingredients": [], "price": None,
         "note": "実験シリーズ。度数が5%超になることも"},
        {"name": "カボセットショコラ", "abv": 4, "volume_ml": 375,
         "sub_ingredients": ["カボス", "ココアパウダー", "蜂蜜"], "price": 2700,
         "note": "フランス菓子オランジェットを思わせる季節限定デザート酒。火入れ"},
    ],

    # やまね酒造（埼玉県飯能市）/ 副原料は「飯能産」が正（狭山茶は誤り）
    "yamane": [
        {"name": "やまねのみのり（茶Ver.）", "abv": None, "volume_ml": 300,
         "sub_ingredients": ["飯能産茶葉"], "price": 1500,
         "note": "全量袋吊り搾り。米・米麹に飯能産茶葉"},
        {"name": "やまねのみのり（蜂蜜Ver.）", "abv": None, "volume_ml": 300,
         "sub_ingredients": ["飯能産蜂蜜"], "price": 1500,
         "note": "全量袋吊り搾り。米・米麹に蜂蜜"},
        {"name": "やまねのみのり（発芽玄米Ver.）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["発芽玄米"], "price": None,
         "note": "公式に発芽玄米Verの言及あり。詳細仕様非開示"},
    ],

    # 平和どぶろく兜町醸造所（東京）/ 看板3副原料 + 本日のどぶろく
    "heiwa-kabutocho": [
        {"name": "平和どぶろく プレーン", "abv": 9, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 1320,
         "note": "店内提供70ml/500円"},
        {"name": "平和どぶろく 小豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["小豆"], "price": None,
         "note": "看板副原料3種の一つ"},
        {"name": "平和どぶろく 黒豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["黒豆"], "price": None,
         "note": "看板副原料3種の一つ"},
        {"name": "平和どぶろく ホップ", "abv": 9, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 1760,
         "note": "看板副原料3種の一つ"},
        {"name": "本日のどぶろく（生姜など）", "abv": None, "volume_ml": 70,
         "sub_ingredients": ["季節副原料"], "price": 550,
         "note": "店内日替り。生姜等"},
    ],

    # 平和どぶろく難波醸造所（大阪・なんば高島屋B1F）
    "heiwa-namba": [
        {"name": "どぶろく プレーン", "abv": 9, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 1452,
         "note": "店内提供70ml/500円・120ml/950円"},
        {"name": "どぶろく 小豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["小豆"], "price": None, "note": "兜町と共通の看板副原料"},
        {"name": "どぶろく 黒豆", "abv": None, "volume_ml": None,
         "sub_ingredients": ["黒豆"], "price": None, "note": "兜町と共通の看板副原料"},
        {"name": "どぶろく ホップ", "abv": 9, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 1936, "note": "兜町と共通の看板副原料"},
        {"name": "どぶろく 白麹", "abv": 9, "volume_ml": 720,
         "sub_ingredients": ["白麹（焼酎用）"], "price": 1936,
         "note": "焼酎用白麹仕込みで酸味強め"},
        {"name": "どぶろく 桜（季節限定）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["塩漬け桜葉"], "price": None,
         "note": "塩漬け桜葉を副原料に。春限定"},
        {"name": "どぶろく 抹茶（季節限定）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["抹茶"], "price": None, "note": "季節限定"},
    ],

    # 東京駅酒造場（東京駅エキナカ、はせがわ酒店）
    "tokyo-station": [
        {"name": "東京駅 どぶろく", "abv": 7, "volume_ml": 300,
         "sub_ingredients": ["米のみ"], "price": 1320,
         "note": "エキナカ初醸造。アルコール7%で軽快"},
        {"name": "季節のフルーツどぶろく マンゴー", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["マンゴー果汁"], "price": None,
         "note": "ヨーグルト風の酸+果実の甘み"},
        {"name": "季節のフルーツどぶろく リンゴ", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["リンゴ果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく ぶどう", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["ぶどう果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく 桃", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["桃果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく パイナップル", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["パイナップル果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく みかん", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["みかん果汁"], "price": None, "note": "季節限定"},
        {"name": "季節のフルーツどぶろく ハニーレモン", "abv": 5, "volume_ml": None,
         "sub_ingredients": ["蜂蜜", "レモン"], "price": None, "note": "季節限定"},
    ],

    # 弥栄醸造（新潟）/ 阿部酒造委託でスタート
    "iyasaka": [
        {"name": "ITTEKI（一擲）十割麹酒 Vol.0-1", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["米のみ（米麹100%）"], "price": 2500,
         "note": "新潟県柏崎市宮之下産コシヒカリ100%。阿部酒造委託醸造。米麹のみのため清酒規格外"},
    ],

    # SAKENOVA BREWERY（新潟・佐渡）/ Crafted Series -Brew Note- が自社醸造
    "sakenova": [
        {"name": "Brew Note 001 HONEY", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["蜂蜜"], "price": 3300,
         "note": "離島初クラフトサケ醸造所の初リリース（2025/12/21）"},
        {"name": "Brew Note 002 APPLE & MIKAN", "abv": 12.5, "volume_ml": 720,
         "sub_ingredients": ["佐渡産りんご果汁", "佐渡産みかん果汁"], "price": 3300,
         "note": "麹米山田錦・掛米こしいぶき・精米60%。日本酒度-8.57"},
        {"name": "Brew Note 006 Strawberry", "abv": 12.5, "volume_ml": 720,
         "sub_ingredients": ["佐渡産いちご「越後姫」"], "price": 2750,
         "note": "精米歩合60%。日本酒度-5.93"},
    ],

    # LINNÉ（京都拠点・委託醸造）
    "linne": [
        {"name": "800 大麦", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["大麦麹"], "price": 4967,
         "note": "haccoba委託醸造。COEDO BREWERY川越産大麦+福島米。ICC SAKE AWARD 2025準優勝"},
        {"name": "800 蕎麦", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["蕎麦麹"], "price": 4967,
         "note": "阿部酒造委託醸造（新潟）"},
        {"name": "800 米", "abv": 16, "volume_ml": 500,
         "sub_ingredients": ["米麹のみ"], "price": 4620,
         "note": "阿部酒造委託醸造。米麹100%のため清酒規格外"},
    ],

    # 天郷醸造所（福岡・福智町）/ フルーツSAKE系。副原料=ミント/苺/レモン（旧「米のみ」表記は誤り。2026-05-31公式オンラインショップで再確認）
    "amanosato": [
        {"name": "在る 緒奏（しょそう）720ml", "abv": 16, "volume_ml": 720,
         "sub_ingredients": ["ミント"], "price": 2640,
         "note": "火入れ版¥2,640/おりがらみ生原酒版¥2,750。福岡県産山田錦100%。ふるさと納税出品あり。「ほんのりミント香る」（公式商品名）"},
        {"name": "在る 小暖（こはる）500ml", "abv": None, "volume_ml": 500,
         "sub_ingredients": ["あまおう苺"], "price": 3850,
         "note": "春限定。福智町産あまおう苺の甘み・酸味・香り"},
        {"name": "在る 寒夜（かんや）500ml", "abv": 16, "volume_ml": 500,
         "sub_ingredients": ["レモン"], "price": 2860,
         "note": "原材料: 米(福岡産)・米麹(福岡産)・レモン(福智町産)。生酒/おりがらみ生原酒の2種"},
        # ── 2026/08/09 公式オンラインショップで確認して追加 ──
        {"name": "在る 陽香（ひのか）500ml", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["ほうじ茶（八女産茶葉）"], "price": 2750,
         "note": "八女産ほうじ茶を使用し、米の旨味と芳ばしさが調和した生酒。原料米は福岡県産山田錦100%。2025年7月一般販売開始。精米歩合は公式非公開"},
        # ── 2026/08/31 公式オンラインショップで確認して追加 ──
        {"name": "天郷 Flagship 1st [序]", "abv": 18, "volume_ml": 720,
         "sub_ingredients": ["ハーブ"], "price": 16500,
         "note": "蔵のフラッグシップ第1作で、カンヌ国際映画祭の公認社交界「CANNES GALA」公式提供酒。福智町の立花智幸さんが合鴨農法・農薬不使用で育てたヒノヒカリ100%。醪を押し潰さない槽搾りで、あえて搾り切らずに仕上げる。ハーブの品種は公式に記載なし。精米歩合は公式非公開。2026/08/31時点で売り切れ"},
        {"name": "天郷 Flagship 2nd", "abv": 16, "volume_ml": 720,
         "sub_ingredients": ["レモン（あがのレモン）"], "price": 17600,
         "note": "CANNES GALA公式提供酒の第2作。合鴨農法の農薬不使用山田錦に、エミューに除草を任せて育てた「あがのレモン」を合わせる。発酵中の酵母に雅楽の調べを特定周波数の加振として与える音響技術を用いると公式に記載。精米歩合は公式非公開"},
        {"name": "在る 小暖（こはる）Premium 苺フレーバー酒 500ml", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["いちご（あまおう）"], "price": 4950,
         "note": "「在る 小暖」のプレミアム版。福智町産の無農薬米「夢一献」と福岡県限定生産のブランド苺「あまおう」を使う。強い微発泡のため立てて冷蔵保存し少しずつガスを抜いて開栓するよう公式が注意している。精米歩合は公式非公開"},
    ],

    # NOMU醸造所（沖縄・コザ）
    "nomu": [
        {"name": "シシカム", "abv": 8, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 1800,
         "note": "肉に合う甘酸ニゴリ。500ml/720ml/1800ml展開"},
        {"name": "OFFZAKE（ノンアル甘酒）", "abv": 0, "volume_ml": None,
         "sub_ingredients": ["白麹", "沖縄県産米"], "price": 3150,
         "note": "ノンアル甘酒。プレーン/パイン/島ソルト/黒糖の4種"},
        {"name": "NOMU（クラフトサケ）", "abv": None, "volume_ml": None,
         "sub_ingredients": ["シークヮーサー（予定）"], "price": None,
         "note": "コアライン。シークヮーサー副原料の予定"},
        {"name": "TABERU（食べる酒）", "abv": 14, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 1980,
         "note": "無濾過の濃厚どぶろく"},
    ],

    # 鮭酒造（千葉・多古）
    "salmon-brewery": [
        {"name": "生酛純米酒 鮭（第1弾）", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 1650,
         "note": "千葉県多古町産中生神力（合鴨農法）。精米歩合90%・生酛・無濾過原酒・瓶燗一度火入れ・おりがらみ。43日発酵"},
    ],

    # 土浦醸造（茨城）/ 2026春オープン、銘柄未発表
    "tsuchiura": [],

    # ── 2026/08/31 追加の3蔵。蔵の実在と免許は公式で確認済みだが、
    #    銘柄ごとの度数・容量・価格を一次ソースで取れていないため空にしておく。
    #    土浦醸造と同じく蔵ページに「銘柄情報は調査中です」と出る。
    #    推測で埋めると嘘ゼロが崩れるので、確認できるまでこのまま。
    "hajimari": [],
    "mingura": [],
    "ubu": [],

    # HAKUTSURU SAKE CRAFT（兵庫神戸・白鶴資料館限定）
    "hakutsuru-sakecraft": [
        {"name": "HAKUTSURU SAKE CRAFT No.1", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 4000,
         "note": "白鶴錦100%・精米50%・純米大吟醸。パイン香"},
        {"name": "HAKUTSURU SAKE CRAFT No.2", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 5500,
         "note": "純米大吟醸・酵母2種ブレンド。パインとメロン香。220本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.3", "abv": 17, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 7700,
         "note": "全国新酒鑑評会出品仕様"},
        {"name": "HAKUTSURU SAKE CRAFT No.4", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["ホップ"], "price": 6050,
         "note": "白鶴錦100%・純米大吟醸ベース+ホップ。ロゼ色。208本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.5", "abv": 16, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 7700,
         "note": "白鶴錦100%・精米38%・大吟醸。リンゴ香と上品な甘み"},
        {"name": "HAKUTSURU SAKE CRAFT No.6", "abv": 12, "volume_ml": 720,
         "sub_ingredients": ["神戸産いちご「あきひめ」"], "price": 6600,
         "note": "純米大吟醸ベース+神戸産いちご。229本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.7", "abv": 12, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 6600, "note": "216本限定"},
        {"name": "HAKUTSURU SAKE CRAFT No.15", "abv": 11, "volume_ml": 720,
         "sub_ingredients": ["ハーブ"], "price": 7700,
         "note": "醸造所発酵CO2を循環活用したハーブ香SAKE"},
        {"name": "HAKUTSURU SAKE CRAFT THE PREMIUM 2026", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 111100,
         "note": "白鶴錦100%・精米38%・純米大吟醸。64本限定"},
    ],

    # でじま芳扇堂（長崎・出島）/ 雲・波・友 シリーズ
    "dejima-hosendo": [
        {"name": "芳扇 雲 1st", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 2750,
         "note": "精米92%・白麹仕込み・一度火入れ。ムース状のテクスチャ"},
        {"name": "芳扇 紫雲", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["雲仙市産黒米（古代米）"], "price": 6600,
         "note": "古代黒米使用の紫色どぶろく。250本限定"},
        {"name": "芳扇 吟雲", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 4400,
         "note": "雲シリーズ上位。Tokyo酒チャレンジ2025金賞"},
        {"name": "芳扇 桜雲", "abv": 12, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3850, "note": "雲シリーズ"},
        {"name": "芳扇 雷雲", "abv": 12, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "雲シリーズ"},
        {"name": "芳扇 波 1st", "abv": 15, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 2750,
         "note": "精米80%・岡山県倉敷産雄町・一度火入れ"},
        {"name": "芳扇 友 内田米レイホウ 菩提酛仕込", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300,
         "note": "熊本県阿蘇内田農園レイホウ精米70%・菩提酛"},
        {"name": "芳扇 友 内田米美山錦", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3520, "note": "内田農園美山錦"},
        {"name": "芳扇 友 目黒米雄町", "abv": 13, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "目黒農園雄町"},
        {"name": "芳扇 波 内田米レイホウ 菩提酛仕込", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "波シリーズ・菩提酛版"},
        {"name": "芳扇 波 内田米美山錦", "abv": 14, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3520, "note": "波シリーズ"},
        {"name": "芳扇 波 目黒米雄町", "abv": 17, "volume_ml": 720,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "波シリーズ"},
        {"name": "芳扇 波 ピンクラベル", "abv": 12, "volume_ml": 500,
         "sub_ingredients": ["米のみ"], "price": 3300, "note": "波シリーズ"},
    ],

    # Cultiva糸島醸造所（福岡・糸島）/ 米のテロワール
    "cultiva": [
        {"name": "Sankeinishiki NAGANO 2025BY", "abv": 15, "volume_ml": 500,
         "sub_ingredients": ["米のみ（山恵錦・長野県産）"], "price": 3080,
         "note": "長野県産山恵錦で醸す品種別どぶろく。生酛・木桶仕込み"},
        {"name": "Hinohikari FUKUOKA 2025BY", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["米のみ（ヒノヒカリ・福岡県産）"], "price": 3080,
         "note": "福岡県産ヒノヒカリで醸す品種別どぶろく"},
        {"name": "Yamadanishiki FUKUOKA 2025BY", "abv": 13, "volume_ml": 500,
         "sub_ingredients": ["米のみ（山田錦・福岡県産）"], "price": 3080,
         "note": "福岡県産山田錦で醸す品種別どぶろく"},
    ],
}


def for_brewery(slug):
    return BRANDS.get(slug, [])
